# Generated by Django 2.1.5 on 2019-02-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Author Name')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='Username')),
                ('passowrd', models.CharField(max_length=120, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64, verbose_name='Headline')),
                ('category', models.CharField(choices=[('POL', 'Politics'), ('ART', 'Art'), ('TECH', 'Technology'), ('TRIVIA', 'Trivial')], max_length=6, verbose_name='Category')),
                ('region', models.CharField(choices=[('UK', 'United Kingdom News'), ('EU', 'European News'), ('W', 'World News')], max_length=2, verbose_name='Region')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('details', models.CharField(max_length=512, verbose_name='Details')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
